In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [8]:
for i in range (len(a)):
 a[i]=2+a[i]
print(a)

[5 6 7 8 9]


In [9]:
for i in range (len(a)):
 a[i]=3*a[i]
print(a)

[15 18 21 24 27]


In [10]:
for i in range (len(a)):
 a[i]=a[i]/2
print(a)

[ 7  9 10 12 13]


In [11]:
arr = np.array([1, 2, 3, 6, 4, 5]) 
arr

array([1, 2, 3, 6, 4, 5])

In [13]:
arr=arr[::-1]
print(arr)

[5 4 6 3 2 1]


In [16]:
 x = np.array([1,2,3,4,5,1,2,1,1,1]) 
 y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
values, counts = np.unique(x, return_counts=True)

max_value = values[np.argmax(counts)]

indices = np.where(x == max_value)[0]
print("most frequent in x:",max_value)
print("at",indices)

most frequent in x: 1
at [0 5 7 8 9]


In [17]:
values, counts = np.unique(y, return_counts=True)

max_value = values[np.argmax(counts)]

indices = np.where(y == max_value)[0]
print("most frequent in y:",max_value)
print("at",indices)

most frequent in y: 1
at [0 1 2]


In [23]:
 arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(int(arr[0][1]))
print(int(arr[2][0]))

20
70


In [26]:
robin = np.linspace(10,100,25)
print(robin)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [35]:
print(robin.size)
print(robin.shape)
print(robin.dtype)
print(robin.ndim)
print("Total bytes:", robin.nbytes)
robin_2D = robin.reshape(5,5)

print("\n2-D Array:")
print(robin_2D)

print("\nTranspose using reshape:")
print(robin_2D.reshape(5,5).T)


25
(25,)
float64
1
Total bytes: 200

2-D Array:
[[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]

Transpose using reshape:
[[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


In [41]:
ucs420_robin=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(np.mean(ucs420_robin))
print(np.median(ucs420_robin))
print(int(np.max(ucs420_robin)))
print(int(np.min(ucs420_robin)))
print(np.unique(ucs420_robin))



43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]


In [42]:
reshaped_ucs420_robin=ucs420_robin.reshape(4,3)
print(reshaped_ucs420_robin)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [45]:
resized_ucs420_robin = np.resize(ucs420_robin, (2,3))

print(resized_ucs420_robin)

[[10 20 30]
 [40 50 60]]
